#!/bin/bash

docker build \
    --build-arg UPDATE_DB=$UPDATE_DB \
    --build-arg NVD_API_KEY=$NVD_API_KEY \
    --build-arg OSSINDEX_PASSWORD=$OSSINDEX_PASSWORD \
    --build-arg OSSINDEX_USERNAME=$OSSINDEX_USERNAME \
    --build-arg NVD_API_DELAY=$NVD_API_DELAY \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
